<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8">
	<meta name="description" content="portfolio de Mlle PADE Marie">
	<meta name="author" content="Marie Pade">
	<title>Portfolio Marie Pade</title>
	<link rel="stylesheet" href="style/stylesheet.css" type="text/css"/>
	<link rel="stylesheet" href="style/my_style.css" media="screen">
	<link rel="stylesheet" type="text/css" href="style/onepage-scroll.css">

</head>

<body>
	<div class="main">
		<section id="section0">
			<header id="tete">
				<nav>
					<a class="cible-section1 current" id="index" href="index.phtml">Home</a>
					<a class="cible-section2" id="profil" href="#section1">Profil</a>
					<a class="cible-section3" id="pScolaire" href="#section2">Parcours Scolaire</a>
					<a class="cible-section4" id="portfolio" href="#section3">Portfolio</a>
					<a class="cible-section5" id="contact" href="#section4">Contact</a>
				</nav>

				<div id="en-tete">
					<img class="picOfMe" src="images/profil.jpg" alt="">
					<p id="nom">PADE Marie</p>
					<p id="statut">Frontend développeuse</p>
				</div>

				<div id="rappel">
					<a class="cible-section2" id="profil2" href="#section1">Profil</a>
					<a class="cible-section3" id="pScolaire2" href="#section2">Parcours Scolaire</a>
					<a class="cible-section4" id="portfolio2" href="#section3">Portfolio</a>
					<a class="cible-section5" id="contact2" href="#section4">Contact</a>
				</div>

				<p>
					Pour ma seconde année, je suis à la recherche d'un contrat en alternance.
					<a href="content/cv.pdf" class="curi">Curriculum vitæ</a>
				</p>
			</header>
		</section>

		<section>
			<div id="section1" class="profil1">
				<h1>Qui suis-je ?</h1>
				<img src="images/picMe2.jpg" id="perso" alt="">
				<p>
					Jeune femme de 23 ans, qui, suite à une reconversion professionnelle, ai décidée de reprendre mes études dans ce qui me plait réellement.
				</p>
				<p>
					Munis d'un BEP Carrière Sanitaire &amp; Social, qui ma permis de développer un sens à l'écoute des autres hors du commun. Suivis d'un emploi de "swing" (assistant manager), j'ai acquis la rigueur des responsabilités et appris à gérer toute forme de stress en cas de deadline courte. Pour finir, avant de faire ce que je fais aujourd'hui, j'ai été directrice d'une franchise de restauration pendant deux belles années, qui de ce côté mon permis d'apprendre la gestion d'équipe, du temps de travail et une organisation à toute épreuves.
				</p>
				<p>
					En Aout 2014, je suis partis en piscine de langage C dans l'école 42, durant 1 mois. Non retenus je suis à présent étudiante au Samsung Campus, une formation en partenariat avec l'école Epitech ainsi que l'association Zup&amp;Co. Cette formation, regroupe tout ce que je voulais améliorer, ainsi qu'apprendre de nouvelles choses. Des nouvelles technologies en constante évolution, permettent d'assouvir mon gout pour les challenges.
				</p>
				<p>
					Mes centres d'intérets sont : les ordinateurs, le cinéma, la littérature, la peinture, la musique, manger(surtout des gâteaux).
				</p>
				<p>
					Je parle : Anglais(niveau intermédiaire), Espagnol(niveau scolaire), Japonais(niveau correct), Coréen(niveau débutant).
					<a href="content/cv.pdf" class="curi">Curriculum vitæ</a>
				</p>
			</div>
		</section>

		<section>
			<div id="section2" class="parcour">
				<h2>Mon parcours scolaire avec les compétences acquise</h2>
				<img src="images/samCam.png" id="logo1" alt="">
				<p>Rentrée en septembre 2014, en association avec <strong>Zup&amp;Co</strong> &amp; l'école <strong>Epitech</strong>.</p>
				<div id="logo">
					<div class="pic">
						<img src="images/php.png" id="php" alt="">
						<p>50%</p>
					</div>
					<div class="pic">
						<img src="images/HTML5.jpg" id="html" alt="">
						<p>75%</p>
					</div>
					<div class="pic">
						<img src="images/cssYeah.png" id="css" alt="">
						<p>75%</p>
					</div>
					<div class="clear">&nbsp;</div>

					<div class="pic">
						<img src="images/javaScript.png" id="js" alt="">
						<p>45%</p>
					</div>
					<div class="pic">
						<img src="images/jquery.png" id="query" alt="">
						<p>40%</p>
					</div>
					<div class="pic">
						<img src="images/mysql.png" id="sql" alt="">
						<p>80%</p>
					</div>
					<div class="clear">&nbsp;</div>

					<div class="pic">
						<img src="images/ps.jpeg" id="ps" alt="">
						<p>60%</p>
					</div>
					<div class="pic">
						<img src="images/cake.jpeg" id="cake" alt="">
						<p>40%</p>
					</div>
					<div class="pic">
						<img src="images/laravoul.png" id="laravel" alt="">
						<p>10%</p>
					</div>
					<div class="clear">&nbsp;</div>
				</div>
				<div id="etedeux">
					<img src="images/42.jpg" id="quarente" alt="">
					<p>Piscine de langage C à l'école <strong>42</strong> durant le mois d'aôut 2014.</p>
				</div>
			</div>
		</section>

		<section>
			<div id="section3" class="port">
				<h3>Mes traveaux</h3>
				<div id="s1">
					<div id="maquette">
						<img class="sem1" id="pro1" alt="" src="images/maquett1.png">
						<img class="sem1" id="pro2" alt="" src="images/maquette2.png">
						<img class="sem1" id="pro3" alt="" src="images/maquette3.png">
						<img class="sem1" id="pro4" alt="" src="images/maquetteRes.png">
					</div>
					<div id="jquery">
						<img class="sem1" id="pro5" alt="" src="images/jquerypart1.png">
					</div>
					<div id="javascript">
						<img class="sem1" id="pro8" alt="" src="images/2048.png">
					</div>
					<div id="phpBloup">
						<img class="sem1" id="pro9" alt="" src="images/my_cinema.png">
						<img class="sem1" id="pro10" alt="" src="images/meetic.png">
					</div>
				</div>

				<div id="popSem1">

					<div id="popin">

						<div class="overlay"></div><!--fin de a div overlay-->

						<div class="popin-container">

							<div class="popin">

								<div class="header">
									<p>Maquette 1</p>
								</div><!--fin de la div header-->
								<img src="images/maquett1.png" id="oh" alt="">
								<p>Reproduire un page vitrine, HTML4/CSS2</p>

								<button id="closeup">fermer</button>

							</div><!--fin de la class popin-->

						</div><!--fin de la div popin-container-->

					</div><!--fin de la div popin-->

					<div id="popin2">

						<div class="overlay"></div><!--fin de a div overlay-->

						<div class="popin-container2">

							<div class="popin2">

								<div class="header2">
									<p>Maquette 2</p>
								</div><!--fin de la div header-->
								<img src="images/maquette2.png" id="deux" alt="">
								<p>Reproduire un page vitrine, HTML5/CSS3</p>

								<button id="closeup2">fermer</button>

							</div><!--fin de la class popin-->

						</div><!--fin de la div popin-container-->

					</div><!--fin de la div popin-->

					<div id="popin3">

						<div class="overlay"></div><!--fin de a div overlay-->

						<div class="popin-container3">

							<div class="popin3">

								<div class="header3">
									<p>Maquette 2</p>
								</div><!--fin de la div header-->
								<img src="images/maquette3.png" id="trois" alt="">
								<p>Reproduire un page vitrine, HTML5/CSS3</p>

								<button id="closeup3">fermer</button>

							</div><!--fin de la class popin-->

						</div><!--fin de la div popin-container-->

					</div><!--fin de la div popin-->

					<div id="popin4">

						<div class="overlay"></div><!--fin de a div overlay-->

						<div class="popin-container4">

							<div class="popin4">

								<div class="header4">
									<p>Maquette Responsive</p>
								</div><!--fin de la div header-->
								<img src="images/maquetteRes.png" id="quatre" alt="">
								<p>Reproduire un page vitrine, HTML5/CSS3</p>

								<button id="closeup4">fermer</button>

							</div><!--fin de la class popin-->

						</div><!--fin de la div popin-container-->

					</div><!--fin de la div popin-->

					<div id="popin5">

						<div class="overlay"></div><!--fin de a div overlay-->

						<div class="popin-container5">

							<div class="popin5">

								<div class="header5">
									<p>Projet jQuery</p>
								</div><!--fin de la div header-->
								<img src="images/jquerypart1.png" id="cinq" alt="">
								<p>Crée avec jQuery, un slider, un drag'n drop, une calculatrice.</p>

								<button id="closeup5">fermer</button>

							</div><!--fin de la class popin-->

						</div><!--fin de la div popin-container-->

					</div><!--fin de la div popin-->

					<div id="popin6">

						<div class="overlay"></div><!--fin de a div overlay-->

						<div class="popin-container6">

							<div class="popin6">

								<div class="header6">
									<p>Projet 2048</p>
								</div><!--fin de la div header-->
								<img src="images/2048.png" id="six" alt="">
								<p>Reproduire le jeu 2048 en javascript/jQuery.</p>

								<button id="closeup6">fermer</button>

							</div><!--fin de la class popin-->

						</div><!--fin de la div popin-container-->

					</div><!--fin de la div popin-->

					<div id="popin7">

						<div class="overlay"></div><!--fin de a div overlay-->

						<div class="popin-container7">

							<div class="popin7">

								<div class="header7">
									<p>Projet my_cinema</p>
								</div><!--fin de la div header-->
								<img src="images/my_cinema.png" id="sept" alt="">
								<p>Création d'une caisse de cinéma avec base de donnée en PHP</p>

								<button id="closeup7">fermer</button>

							</div><!--fin de la class popin-->

						</div><!--fin de la div popin-container-->

					</div><!--fin de la div popin-->

					<div id="popin8">

						<div class="overlay"></div><!--fin de a div overlay-->

						<div class="popin-container8">

							<div class="popin8">

								<div class="header8">
									<p>Projet my_meetic</p>
								</div><!--fin de la div header-->
								<img src="images/meetic.png" id="huit" alt="">
								<p>Création d'un site de rencontre. PHP/HTML5/CSS3</p>

								<button id="closeup8">fermer</button>

							</div><!--fin de la class popin-->

						</div><!--fin de la div popin-container-->

					</div><!--fin de la div popin-->


				</div>

				<div id="s2">
					<div id="phpAvance">
						<img class="sem2" id="pro12" alt="" src="images/tweet.png">
					</div>
					<div id="jsAvance">
						<img class="sem2" id="pro14" alt="" src="images/mapsv1.png">
						<img class="sem2" id="pro15" alt="" src="images/mapsv2.png">
						<img class="sem2" id="pro17" alt="" src="images/paint.png">
					</div>

					<div id="popSem2">
						<div id="popin9">

							<div class="overlay"></div><!--fin de a div overlay-->

							<div class="popin-container9">

								<div class="popin9">

									<div class="header9">
										<p>Projet my_twitter</p>
									</div><!--fin de la div header-->
									<img src="images/tweet.png" id="neuf" alt="">
									<p>Recréer le site de réseau social, twitter. PHP/HTML5/CSS3/JAVASCRIPT</p>

									<button id="closeup9">fermer</button>

								</div><!--fin de la class popin-->

							</div><!--fin de la div popin-container-->

						</div><!--fin de la div popin-->

						<div id="popin10">

							<div class="overlay"></div><!--fin de a div overlay-->

							<div class="popin-container10">

								<div class="popin10">

									<div class="header10">
										<p>Projet my_maps V1</p>
									</div><!--fin de la div header-->
									<img src="images/mapsv1.png" id="dix" alt="">
									<p>Créer un site de cartographie, en utilisant l'API Google. Jquery</p>

									<button id="closeup10">fermer</button>

								</div><!--fin de la class popin-->

							</div><!--fin de la div popin-container-->

						</div><!--fin de la div popin-->

						<div id="popin11">

							<div class="overlay"></div><!--fin de a div overlay-->

							<div class="popin-container11">

								<div class="popin11">

									<div class="header11">
										<p>Projet my_maps V2</p>
									</div><!--fin de la div header-->
									<img src="images/mapsv2.png" id="onze" alt="">
									<p>Trouver une problématique en utilisant l'API Google.</p>

									<button id="closeup11">fermer</button>

								</div><!--fin de la class popin-->

							</div><!--fin de la div popin-container-->

						</div><!--fin de la div popin-->

						<div id="popin12">

							<div class="overlay"></div><!--fin de a div overlay-->

							<div class="popin-container12">

								<div class="popin12">

									<div class="header12">
										<p>Projet my_paint</p>
									</div><!--fin de la div header-->
									<img src="images/paint.png" id="douze" alt="">
									<p>Recoder les fonctionnalités principale de Paint. Jquery/HTML5/CSS3</p>

									<button id="closeup12">fermer</button>

								</div><!--fin de la class popin-->

							</div><!--fin de la div popin-container-->

						</div><!--fin de la div popin-->
					</div>
				</div>
			</div>
		</section>

		<section>
			<div id="section4" class="contactMoi">
				<h4>Contactez moi</h4>
				<p>Toujours joignable, partout, tout le temps !</p>
				<a href="https://www.facebook.com/marie.padereskideguerelle"><img src="images/fac.png" alt="" id="facebook"></a>
				<a href="https://twitter.com/lafillepapillon"><img src="images/twit.jpg" alt="" id="twitter"></a>
				<a href="https://fr.linkedin.com/pub/marie-pade/b6/ba0/873"><img src="images/linkedin.png" alt="" id="link"></a>
				<a href="https://github.com/polaristars"><img src="images/GitHub-Mark.png" id="git" alt=""></a>
				<a href="mailto:pade.marie@gmail.com"><img src="images/mail.png" alt="" id="mailMoi"></a>
			</div>
		</section>
	</div>

	<footer>création de marie pade, portfolio 2015</footer>


	<script type="text/javascript" src="javascript/jquery-1.11.2.min.js"></script>
	<script type="text/javascript" src="javascript/script.js"></script>
	<script type="text/javascript" src="javascript/jquery.onepage-scroll.js"></script>
	<script type="text/javascript">
	$(".main").onepage_scroll({
		sectionContainer: "section",
		easing: "ease",
		animationTime: 1000,
		pagination: true,
		updateURL: false,
		beforeMove: function(index) {},
		afterMove: function(index) {},
		loop: false,
		keyboard: true,
		responsiveFallback: false,
		direction: "vertical"
	});
	</script>

</body>
</html>