<?php
require_once'Ajout.php';
require_once'Bdd.php';
?>
<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8">
	<meta name="description" content="portfolio de Mlle PADE Marie">
	<meta name="author" content="Marie Pade">
	<title>Marie Pade/Admin Panel</title>
	<link rel="stylesheet" href="style.css">

</head>

<body>

	<h1>Bonjour toi :3</h1>

	<div id="addPort">
		<p>Ajouter un projet</p>
		<form method="get">
			<input type="file" enctype="multipart/form-data">
			<button type="submit">Go</button>
		</form>
	</div>
</body>